#spring:
#  profiles:
#    active: dev
#---
#server:
#  port: 8090
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#---
#server:
#  port: 8091
#
#spring:
#  config:
#    activate:
#      on-profile: test
#---
#server:
#  port: 8092
#
#spring:
#  config:
#    activate:
#      on-profile: pro
#---
#
